language: csharp
mono: none
sudo: false
dotnet: 2.2.100
script: "./build.sh --travis"
git:
  depth: false
env:
  global:
    secure: Nfq2JAu7J5n37ghSMVwkGm079fIwZECpvwUeD/OspY7eKszQsykwrHmm1An2S0mnoRl2ONmhS+tL5hINRStDMmWVRugtLSWlnJZQzzuxnG8ZSzSfafKZpCyM4nmk2JWyHenPlAGUzUbvGbwj+IRbN82ghz9Y6SsTbqbp+CPLP8nXpqbOpYpgFVi+8NSYJdZZ/C4yjr0GmYp+z1O+YYTCU0YR0bKhUKX9Btsl6+t9UAzaJ2Yw1ls3Zn0SziC2zIgK3C56wd2OskjFnKSMvm68SgVg85QJFLeU8RH2F7WPMDSmOZGrr5pWvcLQjOUBudTSFRcsPU8fpu9nnM5Cd3BxOqogpOcOH0+34e1dyVwy0eMLiS6jvtQPiocR78aksFr8By+2o0+WHZnPkKRcJql0PU5YfIuCI4QIdQojQcmA6LkxmVb8pteB4Ty4GsELwU5CeSG3Z0/SGkdhij6hYtArIsDNrXH34EpXtaXfO7hrmOmTFnxQyYAIOqLWs0oOd5jJIj5b3GDOFMAcwgQQplHpIYjXOA9kPGRVixM/pqZ0U7ALiPXs64y+Avo3jfJoTn9A5XPWQeAVli0IQIiRRuMurPHAStsL6LSMkLf2s0OtZ6etch5lv2iMuk7cLQV/+WAZ5YJi0Kh6Syw4aIUyV6lP0Z3LQE3PyfXxCG8IRkfMpCI=
